# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Airport(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Airport()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAirport(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Airport
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Airport
    def Icao(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Airport
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Airport
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Airport
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Airport
    def Elevation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Airport
    def TransitionAltitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Airport
    def TransitionLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Airport
    def SpeedLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Airport
    def SpeedLimitAltitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Airport
    def Runways(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Runway import Runway
            obj = Runway()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Airport
    def RunwaysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Airport
    def RunwaysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Airport
    def Procedures(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Procedure import Procedure
            obj = Procedure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Airport
    def ProceduresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Airport
    def ProceduresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def AirportStart(builder):
    builder.StartObject(11)

def Start(builder):
    AirportStart(builder)

def AirportAddIcao(builder, icao):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(icao), 0)

def AddIcao(builder, icao):
    AirportAddIcao(builder, icao)

def AirportAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    AirportAddName(builder, name)

def AirportAddLat(builder, lat):
    builder.PrependFloat32Slot(2, lat, 0.0)

def AddLat(builder, lat):
    AirportAddLat(builder, lat)

def AirportAddLon(builder, lon):
    builder.PrependFloat32Slot(3, lon, 0.0)

def AddLon(builder, lon):
    AirportAddLon(builder, lon)

def AirportAddElevation(builder, elevation):
    builder.PrependInt32Slot(4, elevation, 0)

def AddElevation(builder, elevation):
    AirportAddElevation(builder, elevation)

def AirportAddTransitionAltitude(builder, transitionAltitude):
    builder.PrependInt32Slot(5, transitionAltitude, 0)

def AddTransitionAltitude(builder, transitionAltitude):
    AirportAddTransitionAltitude(builder, transitionAltitude)

def AirportAddTransitionLevel(builder, transitionLevel):
    builder.PrependInt32Slot(6, transitionLevel, 0)

def AddTransitionLevel(builder, transitionLevel):
    AirportAddTransitionLevel(builder, transitionLevel)

def AirportAddSpeedLimit(builder, speedLimit):
    builder.PrependInt32Slot(7, speedLimit, 0)

def AddSpeedLimit(builder, speedLimit):
    AirportAddSpeedLimit(builder, speedLimit)

def AirportAddSpeedLimitAltitude(builder, speedLimitAltitude):
    builder.PrependInt32Slot(8, speedLimitAltitude, 0)

def AddSpeedLimitAltitude(builder, speedLimitAltitude):
    AirportAddSpeedLimitAltitude(builder, speedLimitAltitude)

def AirportAddRunways(builder, runways):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(runways), 0)

def AddRunways(builder, runways):
    AirportAddRunways(builder, runways)

def AirportStartRunwaysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRunwaysVector(builder, numElems):
    return AirportStartRunwaysVector(builder, numElems)

def AirportAddProcedures(builder, procedures):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(procedures), 0)

def AddProcedures(builder, procedures):
    AirportAddProcedures(builder, procedures)

def AirportStartProceduresVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartProceduresVector(builder, numElems):
    return AirportStartProceduresVector(builder, numElems)

def AirportEnd(builder):
    return builder.EndObject()

def End(builder):
    return AirportEnd(builder)
