# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AirportComm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AirportComm()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAirportComm(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AirportComm
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AirportComm
    def AreaCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def IcaoCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def AirportIcao(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def CommType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AirportComm
    def FrequencyUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def ServiceIndicator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def Callsign(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AirportComm
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AirportComm
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def AirportCommStart(builder):
    builder.StartObject(10)

def Start(builder):
    AirportCommStart(builder)

def AirportCommAddAreaCode(builder, areaCode):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(areaCode), 0)

def AddAreaCode(builder, areaCode):
    AirportCommAddAreaCode(builder, areaCode)

def AirportCommAddIcaoCode(builder, icaoCode):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(icaoCode), 0)

def AddIcaoCode(builder, icaoCode):
    AirportCommAddIcaoCode(builder, icaoCode)

def AirportCommAddAirportIcao(builder, airportIcao):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(airportIcao), 0)

def AddAirportIcao(builder, airportIcao):
    AirportCommAddAirportIcao(builder, airportIcao)

def AirportCommAddCommType(builder, commType):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(commType), 0)

def AddCommType(builder, commType):
    AirportCommAddCommType(builder, commType)

def AirportCommAddFrequency(builder, frequency):
    builder.PrependFloat32Slot(4, frequency, 0.0)

def AddFrequency(builder, frequency):
    AirportCommAddFrequency(builder, frequency)

def AirportCommAddFrequencyUnits(builder, frequencyUnits):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(frequencyUnits), 0)

def AddFrequencyUnits(builder, frequencyUnits):
    AirportCommAddFrequencyUnits(builder, frequencyUnits)

def AirportCommAddServiceIndicator(builder, serviceIndicator):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(serviceIndicator), 0)

def AddServiceIndicator(builder, serviceIndicator):
    AirportCommAddServiceIndicator(builder, serviceIndicator)

def AirportCommAddCallsign(builder, callsign):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(callsign), 0)

def AddCallsign(builder, callsign):
    AirportCommAddCallsign(builder, callsign)

def AirportCommAddLat(builder, lat):
    builder.PrependFloat32Slot(8, lat, 0.0)

def AddLat(builder, lat):
    AirportCommAddLat(builder, lat)

def AirportCommAddLon(builder, lon):
    builder.PrependFloat32Slot(9, lon, 0.0)

def AddLon(builder, lon):
    AirportCommAddLon(builder, lon)

def AirportCommEnd(builder):
    return builder.EndObject()

def End(builder):
    return AirportCommEnd(builder)
