# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Edge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Edge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Edge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Edge
    def Nfrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Edge
    def Nend(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Edge
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Edge
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def EdgeStart(builder):
    builder.StartObject(4)

def Start(builder):
    EdgeStart(builder)

def EdgeAddNfrom(builder, nfrom):
    builder.PrependInt32Slot(0, nfrom, 0)

def AddNfrom(builder, nfrom):
    EdgeAddNfrom(builder, nfrom)

def EdgeAddNend(builder, nend):
    builder.PrependInt32Slot(1, nend, 0)

def AddNend(builder, nend):
    EdgeAddNend(builder, nend)

def EdgeAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    EdgeAddName(builder, name)

def EdgeAddLevel(builder, level):
    builder.PrependInt8Slot(3, level, 0)

def AddLevel(builder, level):
    EdgeAddLevel(builder, level)

def EdgeEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdgeEnd(builder)
