# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GLS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GLS()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGLS(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GLS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GLS
    def AreaCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def AirportIcao(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def IcaoCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def RefPathIdent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GLS
    def Runway(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def ApproachBearing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GLS
    def StationLat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GLS
    def StationLon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GLS
    def StationIdent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GLS
    def ApproachSlope(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GLS
    def MagneticVariation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GLS
    def StationElevation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GLS
    def StationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GLSStart(builder):
    builder.StartObject(15)

def Start(builder):
    GLSStart(builder)

def GLSAddAreaCode(builder, areaCode):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(areaCode), 0)

def AddAreaCode(builder, areaCode):
    GLSAddAreaCode(builder, areaCode)

def GLSAddAirportIcao(builder, airportIcao):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(airportIcao), 0)

def AddAirportIcao(builder, airportIcao):
    GLSAddAirportIcao(builder, airportIcao)

def GLSAddIcaoCode(builder, icaoCode):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(icaoCode), 0)

def AddIcaoCode(builder, icaoCode):
    GLSAddIcaoCode(builder, icaoCode)

def GLSAddRefPathIdent(builder, refPathIdent):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(refPathIdent), 0)

def AddRefPathIdent(builder, refPathIdent):
    GLSAddRefPathIdent(builder, refPathIdent)

def GLSAddCategory(builder, category):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(category), 0)

def AddCategory(builder, category):
    GLSAddCategory(builder, category)

def GLSAddChannel(builder, channel):
    builder.PrependInt32Slot(5, channel, 0)

def AddChannel(builder, channel):
    GLSAddChannel(builder, channel)

def GLSAddRunway(builder, runway):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(runway), 0)

def AddRunway(builder, runway):
    GLSAddRunway(builder, runway)

def GLSAddApproachBearing(builder, approachBearing):
    builder.PrependFloat32Slot(7, approachBearing, 0.0)

def AddApproachBearing(builder, approachBearing):
    GLSAddApproachBearing(builder, approachBearing)

def GLSAddStationLat(builder, stationLat):
    builder.PrependFloat32Slot(8, stationLat, 0.0)

def AddStationLat(builder, stationLat):
    GLSAddStationLat(builder, stationLat)

def GLSAddStationLon(builder, stationLon):
    builder.PrependFloat32Slot(9, stationLon, 0.0)

def AddStationLon(builder, stationLon):
    GLSAddStationLon(builder, stationLon)

def GLSAddStationIdent(builder, stationIdent):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(stationIdent), 0)

def AddStationIdent(builder, stationIdent):
    GLSAddStationIdent(builder, stationIdent)

def GLSAddApproachSlope(builder, approachSlope):
    builder.PrependFloat32Slot(11, approachSlope, 0.0)

def AddApproachSlope(builder, approachSlope):
    GLSAddApproachSlope(builder, approachSlope)

def GLSAddMagneticVariation(builder, magneticVariation):
    builder.PrependFloat32Slot(12, magneticVariation, 0.0)

def AddMagneticVariation(builder, magneticVariation):
    GLSAddMagneticVariation(builder, magneticVariation)

def GLSAddStationElevation(builder, stationElevation):
    builder.PrependInt32Slot(13, stationElevation, 0)

def AddStationElevation(builder, stationElevation):
    GLSAddStationElevation(builder, stationElevation)

def GLSAddStationType(builder, stationType):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(stationType), 0)

def AddStationType(builder, stationType):
    GLSAddStationType(builder, stationType)

def GLSEnd(builder):
    return builder.EndObject()

def End(builder):
    return GLSEnd(builder)
