# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GridMora(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GridMora()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGridMora(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GridMora
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GridMora
    def StartLat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GridMora
    def StartLon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GridMora
    def MoraValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GridMora
    def MoraValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GridMora
    def MoraValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def GridMoraStart(builder):
    builder.StartObject(3)

def Start(builder):
    GridMoraStart(builder)

def GridMoraAddStartLat(builder, startLat):
    builder.PrependInt32Slot(0, startLat, 0)

def AddStartLat(builder, startLat):
    GridMoraAddStartLat(builder, startLat)

def GridMoraAddStartLon(builder, startLon):
    builder.PrependInt32Slot(1, startLon, 0)

def AddStartLon(builder, startLon):
    GridMoraAddStartLon(builder, startLon)

def GridMoraAddMoraValues(builder, moraValues):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(moraValues), 0)

def AddMoraValues(builder, moraValues):
    GridMoraAddMoraValues(builder, moraValues)

def GridMoraStartMoraValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMoraValuesVector(builder, numElems):
    return GridMoraStartMoraValuesVector(builder, numElems)

def GridMoraEnd(builder):
    return builder.EndObject()

def End(builder):
    return GridMoraEnd(builder)
