# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Holding(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Holding()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHolding(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Holding
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Holding
    def AreaCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Holding
    def RegionCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Holding
    def IcaoCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Holding
    def WaypointIdentifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Holding
    def HoldingName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Holding
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Holding
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Holding
    def DuplicateIdentifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Holding
    def InboundCourse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Holding
    def TurnDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Holding
    def LegLengthNm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Holding
    def LegTimeMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Holding
    def MinAltitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Holding
    def MaxAltitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Holding
    def SpeedLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def HoldingStart(builder):
    builder.StartObject(15)

def Start(builder):
    HoldingStart(builder)

def HoldingAddAreaCode(builder, areaCode):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(areaCode), 0)

def AddAreaCode(builder, areaCode):
    HoldingAddAreaCode(builder, areaCode)

def HoldingAddRegionCode(builder, regionCode):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(regionCode), 0)

def AddRegionCode(builder, regionCode):
    HoldingAddRegionCode(builder, regionCode)

def HoldingAddIcaoCode(builder, icaoCode):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(icaoCode), 0)

def AddIcaoCode(builder, icaoCode):
    HoldingAddIcaoCode(builder, icaoCode)

def HoldingAddWaypointIdentifier(builder, waypointIdentifier):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(waypointIdentifier), 0)

def AddWaypointIdentifier(builder, waypointIdentifier):
    HoldingAddWaypointIdentifier(builder, waypointIdentifier)

def HoldingAddHoldingName(builder, holdingName):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(holdingName), 0)

def AddHoldingName(builder, holdingName):
    HoldingAddHoldingName(builder, holdingName)

def HoldingAddLat(builder, lat):
    builder.PrependFloat32Slot(5, lat, 0.0)

def AddLat(builder, lat):
    HoldingAddLat(builder, lat)

def HoldingAddLon(builder, lon):
    builder.PrependFloat32Slot(6, lon, 0.0)

def AddLon(builder, lon):
    HoldingAddLon(builder, lon)

def HoldingAddDuplicateIdentifier(builder, duplicateIdentifier):
    builder.PrependInt32Slot(7, duplicateIdentifier, 0)

def AddDuplicateIdentifier(builder, duplicateIdentifier):
    HoldingAddDuplicateIdentifier(builder, duplicateIdentifier)

def HoldingAddInboundCourse(builder, inboundCourse):
    builder.PrependFloat32Slot(8, inboundCourse, 0.0)

def AddInboundCourse(builder, inboundCourse):
    HoldingAddInboundCourse(builder, inboundCourse)

def HoldingAddTurnDirection(builder, turnDirection):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(turnDirection), 0)

def AddTurnDirection(builder, turnDirection):
    HoldingAddTurnDirection(builder, turnDirection)

def HoldingAddLegLengthNm(builder, legLengthNm):
    builder.PrependFloat32Slot(10, legLengthNm, 0.0)

def AddLegLengthNm(builder, legLengthNm):
    HoldingAddLegLengthNm(builder, legLengthNm)

def HoldingAddLegTimeMin(builder, legTimeMin):
    builder.PrependFloat32Slot(11, legTimeMin, 0.0)

def AddLegTimeMin(builder, legTimeMin):
    HoldingAddLegTimeMin(builder, legTimeMin)

def HoldingAddMinAltitude(builder, minAltitude):
    builder.PrependInt32Slot(12, minAltitude, 0)

def AddMinAltitude(builder, minAltitude):
    HoldingAddMinAltitude(builder, minAltitude)

def HoldingAddMaxAltitude(builder, maxAltitude):
    builder.PrependInt32Slot(13, maxAltitude, 0)

def AddMaxAltitude(builder, maxAltitude):
    HoldingAddMaxAltitude(builder, maxAltitude)

def HoldingAddSpeedLimit(builder, speedLimit):
    builder.PrependInt32Slot(14, speedLimit, 0)

def AddSpeedLimit(builder, speedLimit):
    HoldingAddSpeedLimit(builder, speedLimit)

def HoldingEnd(builder):
    return builder.EndObject()

def End(builder):
    return HoldingEnd(builder)
