# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ILS(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ILS()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsILS(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ILS
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ILS
    def RunwayEnd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ILS
    def Ident(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ILS
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ILS
    def Heading(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ILS
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ILS
    def GsAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ILS
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ILS
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ILS
    def Elevation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ILS
    def HasDme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ILS
    def CrossingHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ILSStart(builder):
    builder.StartObject(11)

def Start(builder):
    ILSStart(builder)

def ILSAddRunwayEnd(builder, runwayEnd):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runwayEnd), 0)

def AddRunwayEnd(builder, runwayEnd):
    ILSAddRunwayEnd(builder, runwayEnd)

def ILSAddIdent(builder, ident):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ident), 0)

def AddIdent(builder, ident):
    ILSAddIdent(builder, ident)

def ILSAddFrequency(builder, frequency):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(frequency), 0)

def AddFrequency(builder, frequency):
    ILSAddFrequency(builder, frequency)

def ILSAddHeading(builder, heading):
    builder.PrependFloat32Slot(3, heading, 0.0)

def AddHeading(builder, heading):
    ILSAddHeading(builder, heading)

def ILSAddCategory(builder, category):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(category), 0)

def AddCategory(builder, category):
    ILSAddCategory(builder, category)

def ILSAddGsAngle(builder, gsAngle):
    builder.PrependFloat32Slot(5, gsAngle, 0.0)

def AddGsAngle(builder, gsAngle):
    ILSAddGsAngle(builder, gsAngle)

def ILSAddLat(builder, lat):
    builder.PrependFloat32Slot(6, lat, 0.0)

def AddLat(builder, lat):
    ILSAddLat(builder, lat)

def ILSAddLon(builder, lon):
    builder.PrependFloat32Slot(7, lon, 0.0)

def AddLon(builder, lon):
    ILSAddLon(builder, lon)

def ILSAddElevation(builder, elevation):
    builder.PrependInt32Slot(8, elevation, 0)

def AddElevation(builder, elevation):
    ILSAddElevation(builder, elevation)

def ILSAddHasDme(builder, hasDme):
    builder.PrependBoolSlot(9, hasDme, 0)

def AddHasDme(builder, hasDme):
    ILSAddHasDme(builder, hasDme)

def ILSAddCrossingHeight(builder, crossingHeight):
    builder.PrependInt32Slot(10, crossingHeight, 0)

def AddCrossingHeight(builder, crossingHeight):
    ILSAddCrossingHeight(builder, crossingHeight)

def ILSEnd(builder):
    return builder.EndObject()

def End(builder):
    return ILSEnd(builder)
