# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Marker(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Marker()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMarker(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Marker
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Marker
    def AirportIcao(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Marker
    def RunwayName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Marker
    def LlzIdent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Marker
    def MarkerIdent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Marker
    def MarkerType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Marker
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Marker
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def MarkerStart(builder):
    builder.StartObject(7)

def Start(builder):
    MarkerStart(builder)

def MarkerAddAirportIcao(builder, airportIcao):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(airportIcao), 0)

def AddAirportIcao(builder, airportIcao):
    MarkerAddAirportIcao(builder, airportIcao)

def MarkerAddRunwayName(builder, runwayName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(runwayName), 0)

def AddRunwayName(builder, runwayName):
    MarkerAddRunwayName(builder, runwayName)

def MarkerAddLlzIdent(builder, llzIdent):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(llzIdent), 0)

def AddLlzIdent(builder, llzIdent):
    MarkerAddLlzIdent(builder, llzIdent)

def MarkerAddMarkerIdent(builder, markerIdent):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(markerIdent), 0)

def AddMarkerIdent(builder, markerIdent):
    MarkerAddMarkerIdent(builder, markerIdent)

def MarkerAddMarkerType(builder, markerType):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(markerType), 0)

def AddMarkerType(builder, markerType):
    MarkerAddMarkerType(builder, markerType)

def MarkerAddLat(builder, lat):
    builder.PrependFloat32Slot(5, lat, 0.0)

def AddLat(builder, lat):
    MarkerAddLat(builder, lat)

def MarkerAddLon(builder, lon):
    builder.PrependFloat32Slot(6, lon, 0.0)

def AddLon(builder, lon):
    MarkerAddLon(builder, lon)

def MarkerEnd(builder):
    return builder.EndObject()

def End(builder):
    return MarkerEnd(builder)
