# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Navaid(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Navaid()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNavaid(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Navaid
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Navaid
    def Ident(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Navaid
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Navaid
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Navaid
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Navaid
    def Channel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Navaid
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Navaid
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Navaid
    def Elevation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Navaid
    def RangeNm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Navaid
    def Usage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Navaid
    def SlavedVar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Navaid
    def MagneticVariation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def NavaidStart(builder):
    builder.StartObject(12)

def Start(builder):
    NavaidStart(builder)

def NavaidAddIdent(builder, ident):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ident), 0)

def AddIdent(builder, ident):
    NavaidAddIdent(builder, ident)

def NavaidAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    NavaidAddName(builder, name)

def NavaidAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    NavaidAddType(builder, type)

def NavaidAddFrequency(builder, frequency):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(frequency), 0)

def AddFrequency(builder, frequency):
    NavaidAddFrequency(builder, frequency)

def NavaidAddChannel(builder, channel):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(channel), 0)

def AddChannel(builder, channel):
    NavaidAddChannel(builder, channel)

def NavaidAddLat(builder, lat):
    builder.PrependFloat32Slot(5, lat, 0.0)

def AddLat(builder, lat):
    NavaidAddLat(builder, lat)

def NavaidAddLon(builder, lon):
    builder.PrependFloat32Slot(6, lon, 0.0)

def AddLon(builder, lon):
    NavaidAddLon(builder, lon)

def NavaidAddElevation(builder, elevation):
    builder.PrependInt32Slot(7, elevation, 0)

def AddElevation(builder, elevation):
    NavaidAddElevation(builder, elevation)

def NavaidAddRangeNm(builder, rangeNm):
    builder.PrependInt32Slot(8, rangeNm, 0)

def AddRangeNm(builder, rangeNm):
    NavaidAddRangeNm(builder, rangeNm)

def NavaidAddUsage(builder, usage):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(usage), 0)

def AddUsage(builder, usage):
    NavaidAddUsage(builder, usage)

def NavaidAddSlavedVar(builder, slavedVar):
    builder.PrependFloat32Slot(10, slavedVar, 0.0)

def AddSlavedVar(builder, slavedVar):
    NavaidAddSlavedVar(builder, slavedVar)

def NavaidAddMagneticVariation(builder, magneticVariation):
    builder.PrependFloat32Slot(11, magneticVariation, 0.0)

def AddMagneticVariation(builder, magneticVariation):
    NavaidAddMagneticVariation(builder, magneticVariation)

def NavaidEnd(builder):
    return builder.EndObject()

def End(builder):
    return NavaidEnd(builder)
