# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NavData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NavData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNavData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NavData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NavData
    def Cycle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NavData
    def EffectiveFrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NavData
    def EffectiveTo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NavData
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # NavData
    def Edges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Edge import Edge
            obj = Edge()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def EdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def EdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # NavData
    def Airports(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Airport import Airport
            obj = Airport()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def AirportsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def AirportsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # NavData
    def Navaids(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Navaid import Navaid
            obj = Navaid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def NavaidsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def NavaidsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # NavData
    def Holdings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Holding import Holding
            obj = Holding()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def HoldingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def HoldingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # NavData
    def Markers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.Marker import Marker
            obj = Marker()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def MarkersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def MarkersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # NavData
    def Gls(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.GLS import GLS
            obj = GLS()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def GlsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def GlsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # NavData
    def GridMora(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.GridMora import GridMora
            obj = GridMora()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def GridMoraLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def GridMoraIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # NavData
    def AirportComms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.AirportComm import AirportComm
            obj = AirportComm()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NavData
    def AirportCommsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NavData
    def AirportCommsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

def NavDataStart(builder):
    builder.StartObject(12)

def Start(builder):
    NavDataStart(builder)

def NavDataAddCycle(builder, cycle):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cycle), 0)

def AddCycle(builder, cycle):
    NavDataAddCycle(builder, cycle)

def NavDataAddEffectiveFrom(builder, effectiveFrom):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(effectiveFrom), 0)

def AddEffectiveFrom(builder, effectiveFrom):
    NavDataAddEffectiveFrom(builder, effectiveFrom)

def NavDataAddEffectiveTo(builder, effectiveTo):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(effectiveTo), 0)

def AddEffectiveTo(builder, effectiveTo):
    NavDataAddEffectiveTo(builder, effectiveTo)

def NavDataAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    NavDataAddNodes(builder, nodes)

def NavDataStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems):
    return NavDataStartNodesVector(builder, numElems)

def NavDataAddEdges(builder, edges):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder, edges):
    NavDataAddEdges(builder, edges)

def NavDataStartEdgesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdgesVector(builder, numElems):
    return NavDataStartEdgesVector(builder, numElems)

def NavDataAddAirports(builder, airports):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(airports), 0)

def AddAirports(builder, airports):
    NavDataAddAirports(builder, airports)

def NavDataStartAirportsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAirportsVector(builder, numElems):
    return NavDataStartAirportsVector(builder, numElems)

def NavDataAddNavaids(builder, navaids):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(navaids), 0)

def AddNavaids(builder, navaids):
    NavDataAddNavaids(builder, navaids)

def NavDataStartNavaidsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNavaidsVector(builder, numElems):
    return NavDataStartNavaidsVector(builder, numElems)

def NavDataAddHoldings(builder, holdings):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(holdings), 0)

def AddHoldings(builder, holdings):
    NavDataAddHoldings(builder, holdings)

def NavDataStartHoldingsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartHoldingsVector(builder, numElems):
    return NavDataStartHoldingsVector(builder, numElems)

def NavDataAddMarkers(builder, markers):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(markers), 0)

def AddMarkers(builder, markers):
    NavDataAddMarkers(builder, markers)

def NavDataStartMarkersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMarkersVector(builder, numElems):
    return NavDataStartMarkersVector(builder, numElems)

def NavDataAddGls(builder, gls):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(gls), 0)

def AddGls(builder, gls):
    NavDataAddGls(builder, gls)

def NavDataStartGlsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGlsVector(builder, numElems):
    return NavDataStartGlsVector(builder, numElems)

def NavDataAddGridMora(builder, gridMora):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(gridMora), 0)

def AddGridMora(builder, gridMora):
    NavDataAddGridMora(builder, gridMora)

def NavDataStartGridMoraVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGridMoraVector(builder, numElems):
    return NavDataStartGridMoraVector(builder, numElems)

def NavDataAddAirportComms(builder, airportComms):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(airportComms), 0)

def AddAirportComms(builder, airportComms):
    NavDataAddAirportComms(builder, airportComms)

def NavDataStartAirportCommsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAirportCommsVector(builder, numElems):
    return NavDataStartAirportCommsVector(builder, numElems)

def NavDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return NavDataEnd(builder)
