# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProcLeg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProcLeg()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProcLeg(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProcLeg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProcLeg
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcLeg
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def AltRestriction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcLeg
    def SpeedLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcLeg
    def PathTerminator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcLeg
    def Course(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def DistanceNm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def TurnDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcLeg
    def IsFlyOver(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ProcLeg
    def NavReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcLeg
    def NavLat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def NavLon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def NavBearing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def NavDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def ArcRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def CenterLat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ProcLeg
    def CenterLon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ProcLegStart(builder):
    builder.StartObject(18)

def Start(builder):
    ProcLegStart(builder)

def ProcLegAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ProcLegAddName(builder, name)

def ProcLegAddLat(builder, lat):
    builder.PrependFloat32Slot(1, lat, 0.0)

def AddLat(builder, lat):
    ProcLegAddLat(builder, lat)

def ProcLegAddLon(builder, lon):
    builder.PrependFloat32Slot(2, lon, 0.0)

def AddLon(builder, lon):
    ProcLegAddLon(builder, lon)

def ProcLegAddAltRestriction(builder, altRestriction):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(altRestriction), 0)

def AddAltRestriction(builder, altRestriction):
    ProcLegAddAltRestriction(builder, altRestriction)

def ProcLegAddSpeedLimit(builder, speedLimit):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(speedLimit), 0)

def AddSpeedLimit(builder, speedLimit):
    ProcLegAddSpeedLimit(builder, speedLimit)

def ProcLegAddPathTerminator(builder, pathTerminator):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(pathTerminator), 0)

def AddPathTerminator(builder, pathTerminator):
    ProcLegAddPathTerminator(builder, pathTerminator)

def ProcLegAddCourse(builder, course):
    builder.PrependFloat32Slot(6, course, 0.0)

def AddCourse(builder, course):
    ProcLegAddCourse(builder, course)

def ProcLegAddDistanceNm(builder, distanceNm):
    builder.PrependFloat32Slot(7, distanceNm, 0.0)

def AddDistanceNm(builder, distanceNm):
    ProcLegAddDistanceNm(builder, distanceNm)

def ProcLegAddTurnDirection(builder, turnDirection):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(turnDirection), 0)

def AddTurnDirection(builder, turnDirection):
    ProcLegAddTurnDirection(builder, turnDirection)

def ProcLegAddIsFlyOver(builder, isFlyOver):
    builder.PrependBoolSlot(9, isFlyOver, 0)

def AddIsFlyOver(builder, isFlyOver):
    ProcLegAddIsFlyOver(builder, isFlyOver)

def ProcLegAddNavReference(builder, navReference):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(navReference), 0)

def AddNavReference(builder, navReference):
    ProcLegAddNavReference(builder, navReference)

def ProcLegAddNavLat(builder, navLat):
    builder.PrependFloat32Slot(11, navLat, 0.0)

def AddNavLat(builder, navLat):
    ProcLegAddNavLat(builder, navLat)

def ProcLegAddNavLon(builder, navLon):
    builder.PrependFloat32Slot(12, navLon, 0.0)

def AddNavLon(builder, navLon):
    ProcLegAddNavLon(builder, navLon)

def ProcLegAddNavBearing(builder, navBearing):
    builder.PrependFloat32Slot(13, navBearing, 0.0)

def AddNavBearing(builder, navBearing):
    ProcLegAddNavBearing(builder, navBearing)

def ProcLegAddNavDistance(builder, navDistance):
    builder.PrependFloat32Slot(14, navDistance, 0.0)

def AddNavDistance(builder, navDistance):
    ProcLegAddNavDistance(builder, navDistance)

def ProcLegAddArcRadius(builder, arcRadius):
    builder.PrependFloat32Slot(15, arcRadius, 0.0)

def AddArcRadius(builder, arcRadius):
    ProcLegAddArcRadius(builder, arcRadius)

def ProcLegAddCenterLat(builder, centerLat):
    builder.PrependFloat32Slot(16, centerLat, 0.0)

def AddCenterLat(builder, centerLat):
    ProcLegAddCenterLat(builder, centerLat)

def ProcLegAddCenterLon(builder, centerLon):
    builder.PrependFloat32Slot(17, centerLon, 0.0)

def AddCenterLon(builder, centerLon):
    ProcLegAddCenterLon(builder, centerLon)

def ProcLegEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProcLegEnd(builder)
