# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProcTransition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProcTransition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProcTransition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProcTransition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProcTransition
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProcTransition
    def Legs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.ProcLeg import ProcLeg
            obj = ProcLeg()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProcTransition
    def LegsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProcTransition
    def LegsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ProcTransitionStart(builder):
    builder.StartObject(2)

def Start(builder):
    ProcTransitionStart(builder)

def ProcTransitionAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ProcTransitionAddName(builder, name)

def ProcTransitionAddLegs(builder, legs):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(legs), 0)

def AddLegs(builder, legs):
    ProcTransitionAddLegs(builder, legs)

def ProcTransitionStartLegsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLegsVector(builder, numElems):
    return ProcTransitionStartLegsVector(builder, numElems)

def ProcTransitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProcTransitionEnd(builder)
