# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Procedure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Procedure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProcedure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Procedure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Procedure
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Procedure
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Procedure
    def Runway(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Procedure
    def Legs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.ProcLeg import ProcLeg
            obj = ProcLeg()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Procedure
    def LegsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Procedure
    def LegsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Procedure
    def Transitions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.ProcTransition import ProcTransition
            obj = ProcTransition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Procedure
    def TransitionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Procedure
    def TransitionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def ProcedureStart(builder):
    builder.StartObject(5)

def Start(builder):
    ProcedureStart(builder)

def ProcedureAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ProcedureAddName(builder, name)

def ProcedureAddType(builder, type):
    builder.PrependInt8Slot(1, type, 0)

def AddType(builder, type):
    ProcedureAddType(builder, type)

def ProcedureAddRunway(builder, runway):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(runway), 0)

def AddRunway(builder, runway):
    ProcedureAddRunway(builder, runway)

def ProcedureAddLegs(builder, legs):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(legs), 0)

def AddLegs(builder, legs):
    ProcedureAddLegs(builder, legs)

def ProcedureStartLegsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLegsVector(builder, numElems):
    return ProcedureStartLegsVector(builder, numElems)

def ProcedureAddTransitions(builder, transitions):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(transitions), 0)

def AddTransitions(builder, transitions):
    ProcedureAddTransitions(builder, transitions)

def ProcedureStartTransitionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTransitionsVector(builder, numElems):
    return ProcedureStartTransitionsVector(builder, numElems)

def ProcedureEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProcedureEnd(builder)
