# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Runway(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Runway()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunway(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Runway
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Runway
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Runway
    def Ends(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.RunwayEnd import RunwayEnd
            obj = RunwayEnd()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Runway
    def EndsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Runway
    def EndsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Runway
    def LengthFt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Runway
    def WidthFt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Runway
    def Surface(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Runway
    def Lighting(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Runway
    def Ils(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from NavData.ILS import ILS
            obj = ILS()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Runway
    def IlsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Runway
    def IlsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def RunwayStart(builder):
    builder.StartObject(7)

def Start(builder):
    RunwayStart(builder)

def RunwayAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    RunwayAddName(builder, name)

def RunwayAddEnds(builder, ends):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ends), 0)

def AddEnds(builder, ends):
    RunwayAddEnds(builder, ends)

def RunwayStartEndsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEndsVector(builder, numElems):
    return RunwayStartEndsVector(builder, numElems)

def RunwayAddLengthFt(builder, lengthFt):
    builder.PrependFloat32Slot(2, lengthFt, 0.0)

def AddLengthFt(builder, lengthFt):
    RunwayAddLengthFt(builder, lengthFt)

def RunwayAddWidthFt(builder, widthFt):
    builder.PrependFloat32Slot(3, widthFt, 0.0)

def AddWidthFt(builder, widthFt):
    RunwayAddWidthFt(builder, widthFt)

def RunwayAddSurface(builder, surface):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(surface), 0)

def AddSurface(builder, surface):
    RunwayAddSurface(builder, surface)

def RunwayAddLighting(builder, lighting):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(lighting), 0)

def AddLighting(builder, lighting):
    RunwayAddLighting(builder, lighting)

def RunwayAddIls(builder, ils):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(ils), 0)

def AddIls(builder, ils):
    RunwayAddIls(builder, ils)

def RunwayStartIlsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIlsVector(builder, numElems):
    return RunwayStartIlsVector(builder, numElems)

def RunwayEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunwayEnd(builder)
