# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NavData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunwayEnd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunwayEnd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunwayEnd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunwayEnd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunwayEnd
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunwayEnd
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RunwayEnd
    def Lon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RunwayEnd
    def Heading(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RunwayEnd
    def ElevationFt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RunwayEndStart(builder):
    builder.StartObject(5)

def Start(builder):
    RunwayEndStart(builder)

def RunwayEndAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    RunwayEndAddName(builder, name)

def RunwayEndAddLat(builder, lat):
    builder.PrependFloat32Slot(1, lat, 0.0)

def AddLat(builder, lat):
    RunwayEndAddLat(builder, lat)

def RunwayEndAddLon(builder, lon):
    builder.PrependFloat32Slot(2, lon, 0.0)

def AddLon(builder, lon):
    RunwayEndAddLon(builder, lon)

def RunwayEndAddHeading(builder, heading):
    builder.PrependFloat32Slot(3, heading, 0.0)

def AddHeading(builder, heading):
    RunwayEndAddHeading(builder, heading)

def RunwayEndAddElevationFt(builder, elevationFt):
    builder.PrependInt32Slot(4, elevationFt, 0)

def AddElevationFt(builder, elevationFt):
    RunwayEndAddElevationFt(builder, elevationFt)

def RunwayEndEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunwayEndEnd(builder)
